intelligence/urls.py
from django.urls import path
from . import views

app_name = 'intelligence'

urlpatterns = [
    path('', views.index, name='index'),
    path('calc', views.calc, name='calc'),
    path('result', views.result, name='result')
]

project/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include(('intelligence.urls', 'intelligence'), namespace='intelligence')),
]

intelligence/models.py
from django.db import models

# Create your models here.

intelligence/views.py
from django.shortcuts import render
import numpy as np
from collections import OrderedDict
    
def index(request):
    request.session['num_for'] = 0
    request.session['num_iter'] = 0
    return render(request, 'intelligence/index.html')

def calc(request):
    num_for = request.session.get('num_for') # 0<=num_for<=20
    num_iter = request.session.get('num_iter') #0<=num_iter<=10
    if num_for > 20:
        return render(request, '500.html', status=500)
    if num_for == 20:
        request.session['num_19'] = int(request.POST['num_post'])
        request.session['num_for'] = num_for+1
        request.session['num_iter'] = num_iter + 1
        return render(request, 'intelligence/riamu.html')
    else:
        lis = ["","","","","",""]
        if num_for != 0:
            num_post = int(request.POST['num_post'])
            request.session["num_{}".format(num_for-1)] = num_post
        if num_for%2 == 0:
            arange = np.arange(19)
            np.random.shuffle(arange)
            arange = 19*(num_iter)+arange
            var = []
            for i in range(6):
                var.append(int(arange[i]))
                request.session[f'var_{i}'] = int(var[i])
            text = "1番好きなのを選んでください"
        else:
            var = []
            for i in range(6):
                var.append(int(request.session.get(f'var_{i}')))
            for i in range(6):
                if var[i] == num_post:
                    lis[i] = "class = fav disabled"
                    break
            text = "6番目に好きなのを選んでください"
            request.session['num_iter'] = num_iter + 1
        request.session['num_for'] = num_for + 1
        context = {'var_0':var[0],'var_1':var[1],'var_2':var[2],'var_3':var[3],'var_4':var[4],'var_5':var[5],
                   'number':num_iter+1,'text':text,
                   'lis_0':lis[0],'lis_1':lis[1],'lis_2':lis[2],'lis_3':lis[3],'lis_4':lis[4],'lis_5':lis[5],
                   }
        return render(request, 'intelligence/calc.html',context)      

def result(request):
    def softmax(x):
        if x.ndim == 2:
            x = x.T
            x = x - np.max(x, axis=0)
            y = np.exp(x) / np.sum(np.exp(x), axis=0)
            return y.T 
    
        x = x - np.max(x)
        return np.exp(x) / np.sum(np.exp(x))
    
    def cross_entropy_error(y, t):
        if y.ndim == 1:
            t = t.reshape(1, t.size)
            y = y.reshape(1, y.size)
        t = t.argmax(axis=1)
    
        batch_size = y.shape[0]
    
        return -np.sum(np.log(y[np.arange(batch_size), t] + 1e-7)) / batch_size
    
    def im2col(input_data, filter_h, filter_w, stride=1, pad=0):
        N, C, H, W = input_data.shape
        out_h = (H + 2*pad - filter_h)//stride + 1
        out_w = (W + 2*pad - filter_w)//stride + 1
    
        img = np.pad(input_data, [(0,0), (0,0), (pad, pad), (pad, pad)], 'constant')
        col = np.zeros((N, C, filter_h, filter_w, out_h, out_w))
    
        for y in range(filter_h):
            y_max = y + stride*out_h
            for x in range(filter_w):
                x_max = x + stride*out_w
                col[:, :, y, x, :, :] = img[:, :, y:y_max:stride, x:x_max:stride]
    
        col = col.transpose(0, 4, 5, 1, 2, 3).reshape(N*out_h*out_w, -1)
        return col
    
    def col2im(col, input_shape, filter_h, filter_w, stride=1, pad=0):
        N, C, H, W = input_shape
        out_h = (H + 2*pad - filter_h)//stride + 1
        out_w = (W + 2*pad - filter_w)//stride + 1
        col = col.reshape(N, out_h, out_w, C, filter_h, filter_w).transpose(0, 3, 4, 5, 1, 2)
    
        img = np.zeros((N, C, H + 2*pad + stride - 1, W + 2*pad + stride - 1))
        for y in range(filter_h):
            y_max = y + stride*out_h
            for x in range(filter_w):
                x_max = x + stride*out_w
                img[:, :, y:y_max:stride, x:x_max:stride] += col[:, :, y, x, :, :]
    
        return img[:, :, pad:H + pad, pad:W + pad]
    
    class Relu:
        def __init__(self):
            self.mask = None
    
        def forward(self, x):
            self.mask = (x <= 0)
            out = x.copy()
            out[self.mask] = 0
    
            return out
    
        def backward(self, dout):
            dout[self.mask] = 0
            dx = dout
    
            return dx
        
    class Affine:
        def __init__(self, W, b):
            self.W =W
            self.b = b
            
            self.x = None
            self.original_x_shape = None
            self.dW = None
            self.db = None
    
        def forward(self, x):
            self.original_x_shape = x.shape
            x = x.reshape(x.shape[0], -1)
            self.x = x
    
            out = np.dot(self.x, self.W) + self.b
    
            return out
    
        def backward(self, dout):
            dx = np.dot(dout, self.W.T)
            self.dW = np.dot(self.x.T, dout)
            self.db = np.sum(dout, axis=0)
            
            dx = dx.reshape(*self.original_x_shape)
            return dx  
    
    class SoftmaxWithLoss:
        def __init__(self):
            self.loss = None
            self.y = None
            self.t = None
    
        def forward(self, x, t):
            self.t = t
            self.y = softmax(x)
            self.loss = cross_entropy_error(self.y, self.t)
            
            return self.loss
    
        def backward(self, dout=1):
            batch_size = self.t.shape[0]
            dx = (self.y - self.t) / batch_size
            
            return dx
    
    class Convolution:
        def __init__(self, W, b, stride=1, pad=0):
            self.W = W
            self.b = b
            self.stride = stride
            self.pad = pad
            
            self.x = None   
            self.col = None
            self.col_W = None
            
            self.dW = None
            self.db = None
    
        def forward(self, x):
            FN, C, FH, FW = self.W.shape
            N, C, H, W = x.shape
            out_h = 1 + int((H + 2*self.pad - FH) / self.stride)
            out_w = 1 + int((W + 2*self.pad - FW) / self.stride)
    
            col = im2col(x, FH, FW, self.stride, self.pad)
            col_W = self.W.reshape(FN, -1).T
    
            out = np.dot(col, col_W) + self.b
            out = out.reshape(N, out_h, out_w, -1).transpose(0, 3, 1, 2)
    
            self.x = x
            self.col = col
            self.col_W = col_W
    
            return out
    
        def backward(self, dout):
            FN, C, FH, FW = self.W.shape
            dout = dout.transpose(0,2,3,1).reshape(-1, FN)
    
            self.db = np.sum(dout, axis=0)
            self.dW = np.dot(self.col.T, dout)
            self.dW = self.dW.transpose(1, 0).reshape(FN, C, FH, FW)
    
            dcol = np.dot(dout, self.col_W.T)
            dx = col2im(dcol, self.x.shape, FH, FW, self.stride, self.pad)
    
            return dx
    
    
    class Pooling:
        def __init__(self, pool_h, pool_w, stride=1, pad=0):
            self.pool_h = pool_h
            self.pool_w = pool_w
            self.stride = stride
            self.pad = pad
            
            self.x = None
            self.arg_max = None
    
        def forward(self, x):
            N, C, H, W = x.shape
            out_h = int(1 + (H - self.pool_h) / self.stride)
            out_w = int(1 + (W - self.pool_w) / self.stride)
    
            col = im2col(x, self.pool_h, self.pool_w, self.stride, self.pad)
            col = col.reshape(-1, self.pool_h*self.pool_w)
    
            arg_max = np.argmax(col, axis=1)
            out = np.max(col, axis=1)
            out = out.reshape(N, out_h, out_w, C).transpose(0, 3, 1, 2)
    
            self.x = x
            self.arg_max = arg_max
    
            return out
    
        def backward(self, dout):
            dout = dout.transpose(0, 2, 3, 1)
            
            pool_size = self.pool_h * self.pool_w
            dmax = np.zeros((dout.size, pool_size))
            dmax[np.arange(self.arg_max.size), self.arg_max.flatten()] = dout.flatten()
            dmax = dmax.reshape(dout.shape + (pool_size,)) 
            
            dcol = dmax.reshape(dmax.shape[0] * dmax.shape[1] * dmax.shape[2], -1)
            dx = col2im(dcol, self.x.shape, self.pool_h, self.pool_w, self.stride, self.pad)
            
            return dx
        
    class Dropout:
        def __init__(self, dropout_ratio=0.5):
            self.dropout_ratio = dropout_ratio
            self.mask = None
    
        def forward(self, x, train_flg=True):
            if train_flg:
                self.mask = np.random.rand(*x.shape) > self.dropout_ratio
                return x * self.mask
            else:
                return x * (1.0 - self.dropout_ratio)
    
        def backward(self, dout):
            return dout * self.mask

    class DeepConvNet:
        def __init__(self, input_dim=(1, 28, 28),
                     conv_param_1 = {'filter_num':16, 'filter_size':3, 'pad':1, 'stride':1},
                     conv_param_2 = {'filter_num':32, 'filter_size':3, 'pad':1, 'stride':1},
                     conv_param_3 = {'filter_num':64, 'filter_size':3, 'pad':1, 'stride':1},
                     hidden_size=50, output_size=10):
            pre_node_nums = np.array([1*3*3, 16*3*3, 32*3*3, 64*8*8, hidden_size])
            weight_init_scales = np.sqrt(2.0 / pre_node_nums)
            
            self.params = {}
            pre_channel_num = input_dim[0]
            for idx, conv_param in enumerate([conv_param_1, conv_param_2, conv_param_3]):
                self.params['W' + str(idx+1)] = weight_init_scales[idx] * np.random.randn(conv_param['filter_num'], pre_channel_num, conv_param['filter_size'], conv_param['filter_size'])
                self.params['b' + str(idx+1)] = np.zeros(conv_param['filter_num'])
                pre_channel_num = conv_param['filter_num']

intelligence/templates/intelligence/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="twitter:card" content="summary">
  <meta property="og:title" content="Cinderella Recommend">
  <meta property="og:type" content="website" />
  <meta property="og:description" content="AIがあなたにおすすめの恒常SSRを診断します。">
  <meta property="og:url" content="https://sosei.pythonanywhere.com/">
  <meta property="og:image" content="https://sosei.pythonanywhere.com/static/intelligence/img/main.png">
  <meta name="description" content="AIがあなたにおすすめの恒常SSRを診断します。">
  <link rel="apple-touch-icon" type="image/png" href="{% static "intelligence/img/apple-touch-icon-180x180.png" %}">
  <link rel="icon" type="image/png" href="{% static "intelligence/img/icon-192x192.png" %}">
  <link rel="icon" type="image/vnd.microsoft.icon" href="{% static "intelligence/img/favicon.ico" %}">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}{% endblock title %}</title>
  <link href="{% static "intelligence/css/style.css" %}" rel="stylesheet">
</head>
<body>
  {% block content %}{% endblock %}
</body>
</html>

intelligence/templates/intelligence/calc.html
{% extends "intelligence/base.html" %}
{% load static %}
{% block title %}Cinderella Recommend{% endblock title %}

{% block content %}

  <h3>{{number}}/10</h3>

  <form id="calc" method="post" action="calc">
    {% csrf_token %}
    <button {{lis_0}} type="submit" name="num_post" value="{{var_0}}"><img src="{% static "intelligence/img/rawSR/" %}{{var_0}}.jpg"></button>
    <button {{lis_1}} type="submit" name="num_post" value="{{var_1}}"><img src="{% static "intelligence/img/rawSR/" %}{{var_1}}.jpg"></button>
    <button {{lis_2}} type="submit" name="num_post" value="{{var_2}}"><img src="{% static "intelligence/img/rawSR/" %}{{var_2}}.jpg"></button>
    <button {{lis_3}} type="submit" name="num_post" value="{{var_3}}"><img src="{% static "intelligence/img/rawSR/" %}{{var_3}}.jpg"></button>
    <button {{lis_4}} type="submit" name="num_post" value="{{var_4}}"><img src="{% static "intelligence/img/rawSR/" %}{{var_4}}.jpg"></button>
    <button {{lis_5}} type="submit" name="num_post" value="{{var_5}}"><img src="{% static "intelligence/img/rawSR/" %}{{var_5}}.jpg"></button>
  </form>

  <p>{{text}}</p>
{% endblock %}

intelligence/templates/intelligence/index.html
{% extends "intelligence/base.html" %}
{% load static %}
{% block title %}Cinderella Recommend{% endblock title %}

{% block content %}
  <img id="heroimg" src="{% static "intelligence/img/heroimg.png" %}">
  <div id="instruction">
    <h3>せつめい</h3>
    <ul>
      <li>・6枚の画像がランダムに表示されます。</li>
      <li>・1番好きなのと6番目に好きなのを順に<br>&nbsp;&nbsp;&nbsp;タップしてください。</li>
      <li>・10回選んだらAIがあなたにおすすめの<br>&nbsp;&nbsp;&nbsp;恒常SSRを診断します。</li>
    </ul>
  </div>
  <a href="{%url 'intelligence:calc' %}" class="start-btn">診断開始</a>
  <span class="note">当サイトは<a href="https://twitter.com/kFTRwuDs6Utx">@kFTRwuDs6Utx</a>が運営しています。</span>
  <span class="note">誤字・脱字、不具合等ございましたら<br>ご連絡いただけると幸いです。</span>
{% endblock %}

intelligence/templates/intelligence/result.html
{% extends "intelligence/base.html" %}
{% load static %}
{% block title %}診断結果 - Cinderella Recommend{% endblock title %}

{% block content %}
<h3>診断結果</h3>
<p class="name">1位:{{1st_name}}</p>
<img class="ssr" src="{% static "intelligence/img/rawSSR/" %}{{1st}}.jpg">
<p class="name">2位:{{2nd_name}}</p>
<img class="ssr" src="{% static "intelligence/img/rawSSR/" %}{{2nd}}.jpg">
<p class="name">3位:{{3rd_name}}</p>
<img class="ssr" src="{% static "intelligence/img/rawSSR/" %}{{3rd}}.jpg">
<p class="name">4位:{{4th_name}}</p>
<img class="ssr" src="{% static "intelligence/img/rawSSR/" %}{{4th}}.jpg">
<p class="name">5位:{{5th_name}}</p>
<img class="ssr" src="{% static "intelligence/img/rawSSR/" %}{{5th}}.jpg">

<a class="re-btn" href="{%url 'intelligence:index' %}" class="nav-link">もう一度診断する</a>
{% endblock %}

intelligence/templates/intelligence/riamu.html
{% load static %}
<!DOCTYPE html>

<html lang="ja">

<head>
  <meta http-equiv="refresh" content="0; url={%url 'intelligence:result' %}">
  <meta charset="utf-8">
  <meta name="twitter:card" content="summary">
  <meta property="og:title" content="Cinderella Recommend">
  <meta property="og:type" content="website" />
  <meta property="og:description" content="AIがあなたにおすすめの恒常SSRを診断します。">
  <meta property="og:url" content="https://sosei.pythonanywhere.com/">
  <meta property="og:image" content="https://sosei.com/static/intelligence/img/main.png">
  <meta name="description" content="AIがあなたにおすすめの恒常SSRを診断します。">
  <link rel="apple-touch-icon" type="image/png" href="{% static "intelligence/img/apple-touch-icon-180x180.png" %}">
  <link rel="icon" type="image/png" href="{% static "intelligence/img/icon-192x192.png" %}">
  <link rel="icon" type="image/vnd.microsoft.icon" href="{% static "intelligence/img/favicon.ico" %}">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>AI診断中 - Cinderella Recommend</title>
  <link href="{% static "intelligence/css/style.css" %}" rel="stylesheet">
</head>

<body>

  <h3>AI診断中…</h3>
  <span class="note">計算には約30秒かかりますのでお待ちください。<br>計算終了後、自動的に結果を表示します。</span>
</body>

</html>